---
- hosts: PiSpot_Voucher
  serial: 5 ### MAXIMUM HOSTS TO CONNECT TO AT A SINGLE TIME
  gather_facts: true
  tasks:
  - name: Generate a Wrapped Secret ID
    shell: . /root/.bashrc; vault write -wrap-ttl=30 -f auth/approle/role/pispot_voucher/secret-id metadata='{"hostname":"{{ ansible_hostname }}"}' -format=json | jq '.wrap_info.token'
    delegate_to: localhost
    register: wrapped_secretid

  - name: Clean Wrapped Secret ID
    set_fact:
      wrapped_token_clean: "{{ wrapped_secretid.stdout | replace('\"', '') | replace('\','') }}"

  - name: Upload Python3 script to Unwrap SecretID, get Approle Token and write it to environment
    copy:
      src: pyscripts/get-approle-token.py
      dest: /tmp/get-approle-token.py
      owner: root
      group: root
      mode: a+x

  - name: Get Approle Token
    shell: '. /etc/profile; python3 /tmp/get-approle-token.py "{{ wrapped_token_clean }}"'
